### PR TITLE
Update links in `README.md`

### PR DESCRIPTION
**Pull request by ramikg**

### CODE REVIEW

**Comment by 0xeb** [comment]
Thank you.

Please update this PR and the Python instructions to read:

Python 3.x instead of 2.x.

Since 8.0, Python 2.x is not supported.

**Comment by ramikg** [comment]
Done.
I've also updated multiple details which were no longer correct. Please review these changes.

Thank you.

**Comment by 0xeb** [comment]
@aundro , as I said in my comments above. What Rami added was incorrect:

"Switching the default language between Python and IDC

By default, IDA will use Python to evaluate expressions. It is possible to change the default language to IDC.

In order to do that, use the following Python code:"


This is not true. As it was, it was correct. He misunderstands what that paragraph means.

Can you please revert / fix that paragraph ?

**Comment by ramikg** [comment]
Indeed I have misunderstood the paragraph's meaning.
Hopefully #41 fixes it, and also makes everything clearer.

**Pull request merged**
