### PR TITLE
+ bugfix: IDAPython: Choose.OnGetLineAttr was broken

### PR DESCRIPTION
**Pull request by 0xeb**
- It was only accepting tuples

### CODE REVIEW

**Comment by 0xeb** [comment]
Also, it was buggy because one cannot return a proper uint_32 from that callback, it was causing an error:

`OverflowError: Python int too large to convert to C long ;`

Hence now we extract the color with `PyLong_AsUnsignedLong` instead.

**Comment by aundro** [comment]
Elias,

you wrote:
 * "- It was only accepting tuples", but unless I'm suffering from a severe Monday case, it was only accepting _lists_, not tuples.
 * "- It was leaking references", but looking at the `PyList` API (https://docs.python.org/3/c-api/list.html), `PyList_GetItem` returns a _borrowed_ reference, and thus nothing was leaked (however, it should have been using `borref_t`.)

I like the `operator bool()` thing, but shouldn't we do a pass over the whole plugin then, instead of using it in only 2 places and add more inconsistencies?

**Comment by 0xeb** [comment]
1)

Sorry, you are fine but I was suffering from a "long work hours" myself.

The fix is correct, however I screwed up with the description.

This callback is supposed to accept tuples (and lists) as the documentation states. 
But yes, it was not leaking references.


2)
Let's do another run on the whole sources afterwards in a different PR.

This one should be good to go.

**Comment by aundro** [comment]
@0xeb merged. If you find the time, can you do that pass to use the `operator bool()`  in all places that look like a good match?

**Pull request merged**
