### PR TITLE
+ added highlighting for Python 3.10 keywords

### PR DESCRIPTION
**Pull request by 0xeb**
added support for `match` and `case` keywords

### CODE REVIEW

**Comment by aundro** [comment]
I take it the need to have `add_new_keywords` is justified by the fact that a call to `Py_GetVersion` must happen post-initialization?

**Comment by 0xeb** [comment]
Well, when I looked at the sources, it was usually called after initialized.

Now that you posed that question, I looked at `Py_GetVersion()` implementation and it seems to return a simple string...

https://github.com/python/cpython/blob/a0df9ee8fc77443510ab7e9ba8fd830f255a8fec/Python/getversion.c#L11

I pushed an update, check now please.

**Comment by 0xeb** [comment]
So in summary, code that calls Py_GetVersion() usually wait until Py_Initialize() is called.
However, looking at the implementation, it seems it can be called w/o. I actually tried on both Windows and Linux:

```c++
#include <Python.h>
#include <stdio.h>

int main(int argc, char *argv[]) {
    // Initialize the Python interpreter
    //Py_Initialize();

    // Get the version string
    const char *version = Py_GetVersion();
    int major = 0, minor = 0;
    sscanf(version, "%d.%d", &major, &minor);
    // Print the version string
    printf("Python interpreter version: %d.%d\n", major, minor);

    // Finalize the Python interpreter
    //Py_Finalize();

    return 0;
}
```

So today it works w/o calling init(), also the Python docs don't mention that we need to call init beforehand, etc.

IMHO, I feel it is safer/future proof to ask for the version after we initialize Python.

**Comment by 0xeb** [comment]
Ok,hold on then, let me get the previous commit back on then.

Done, ready to merge then.

**Pull request merged**
